### ISSUE TITLE
ECOS BB calling infeasible unbounded

### ISSUE THREAD

**Issue by SteveDiamond** [embotech/ecos#114]
I think ECOS BB is returning the exit code for unbounded when it should be returning the exit code for infeasible. Here's the problem:

https://github.com/cvxgrp/cvxpy/issues/167

You can get the ECOS BB problem using:

http://www.cvxpy.org/en/latest/tutorial/advanced/index.html#getting-the-standard-form

**Comment by hanwang** [comment]
This problem is caused because the integers used for ECOS_BB exitflags are different from ECOS for non-optimal solutions. I've changed the flags to match the closest ECOS exitflags, however, I recommend implementing a STATUS_MAP for ECOS_BB instead of inheriting the STATUS_MAP from ECOS. I've push the updated flags to branch 'fix.EXITFLAG'

**Comment by SteveDiamond** [comment]
That makes sense to change the STATUS_MAP. I hadn't realized the exit codes
were different. Where are the ECOS_BB exit codes documented?

**Comment by hanwang** [comment]
They'll be in ecos/ecos_bb/ecos_bb.h

**Comment by SteveDiamond** [comment]
Ok, could you write about them in the ECOS README or at least comment
ecos_bb.h? I don't know what the difference is between

#define MI_SOLVED_NON_BRANCHABLE (3) #define MI_SOLVED_BRANCHABLE (2) for
example.

**Comment by hanwang** [comment]
Sure thing, the source has been updated with comments for the exit flags. Feel free to use the comments verbatim as the status explanation for CVXPY.

**Comment by SteveDiamond** [comment]
Wait, are you sure you committed it? It says on github the last update to this repo was 21 days ago.

**Comment by hanwang** [comment]
It's on the 'fix.EXITFLAG' branch.
