### ISSUE TITLE
Exponential cones

### ISSUE THREAD

**Issue by echu** [embotech/ecos#43]
It's late. I should be sleeping.

Anyway, since CVX pioneered the successive approximation approach to handling logarithms, etc. I wonder if for a future goal (say, ECOS 1.2) it might be a good idea for us to bake in the successive approximation directly into the solver. So whenever ECOS sees an exponential cone, it uses a successive approximation technique (presumably by maintaining pointers to the KKT system). Of course, we would print the requisite warning. But this would let us (quickly) solve problems with logarithms in, say, CVXPY.

Of course, we could construct the approximation in CVXPY instead of directly in the solver.... Thoughts?

**Comment by echu** [comment]
Looks like @tiagoakle is merging / has merged his exponential cone work into the dev branch. :)

**Comment by mcg1969** [comment]
If you’re going to bake successive approximation into the solver, then the question becomes when to update the approximation’s center point. Do you converge the approximated problem fully before adjusting the centerpoint, as CVX does, or do you update it more frequently?

And what happens if you update it *at every itereation*?

I argue that this last case is almost precisely what a direct implementation of exponential cones will do.

On Mar 19, 2014, at 4:07 AM, Eric Chu <notifications@github.com<mailto:notifications@github.com>> wrote:


It's late. I should be sleeping.

Anyway, since CVX pioneered the successive approximation approach to handling logarithms, etc. I wonder if for a future goal (say, ECOS 1.2) it might be a good idea for us to bake in the successive approximation directly into the solver. So whenever ECOS sees an exponential cone, it uses a successive approximation technique (presumably by maintaining pointers to the KKT system). Of course, we would print the requisite warning. But this would let us (quickly) solve problems with logarithms in, say, CVXPY.

Of course, we could construct the approximation in CVXPY instead of directly in the solver.... Thoughts?
